### ISSUE TITLE
requirements

### ISSUE THREAD

**Issue by h1alexbel** [h1alexbel/weeks#10]

**Comment by 0pdd** [comment]
@h1alexbel 3 puzzles [#29](https://github.com/h1alexbel/weeks/issues/29), [#30](https://github.com/h1alexbel/weeks/issues/30), [#32](https://github.com/h1alexbel/weeks/issues/32) are still not solved.

**Comment by 0pdd** [comment]
@h1alexbel 4 puzzles [#29](https://github.com/h1alexbel/weeks/issues/29), [#30](https://github.com/h1alexbel/weeks/issues/30), [#32](https://github.com/h1alexbel/weeks/issues/32), [#38](https://github.com/h1alexbel/weeks/issues/38) are still not solved.

**Comment by 0pdd** [comment]
@h1alexbel 2 puzzles [#29](https://github.com/h1alexbel/weeks/issues/29), [#38](https://github.com/h1alexbel/weeks/issues/38) are still not solved; solved: [#30](https://github.com/h1alexbel/weeks/issues/30), [#32](https://github.com/h1alexbel/weeks/issues/32).
